-- Moderation Tables Migration

-- Table: flagged_words
-- Purpose: Store inappropriate words for auto-moderation
CREATE TABLE `flagged_words` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `word` VARCHAR(100) NOT NULL UNIQUE,
    `category` ENUM('profanity', 'hate_speech', 'spam', 'violence', 'sexual') NOT NULL,
    `severity` ENUM('low', 'medium', 'high', 'critical') NOT NULL DEFAULT 'medium',
    `auto_action` ENUM('flag', 'reject') NOT NULL DEFAULT 'flag',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX `idx_word` (`word`),
    INDEX `idx_severity` (`severity`)
) ENGINE=InnoDB;

-- Table: content_violations
-- Purpose: Log all content moderation violations
CREATE TABLE `content_violations` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `content_type` ENUM('comment', 'story', 'action', 'resource') NOT NULL,
    `content_id` INT UNSIGNED NOT NULL,
    `user_id` INT UNSIGNED NOT NULL,
    `flagged_word` VARCHAR(100) NOT NULL,
    `word_category` VARCHAR(50) NOT NULL,
    `severity` VARCHAR(20) NOT NULL,
    `status` ENUM('pending', 'reviewed', 'dismissed') DEFAULT 'pending',
    `reviewed_by` INT UNSIGNED NULL,
    `reviewed_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`reviewed_by`) REFERENCES `users`(`id`) ON DELETE SET NULL,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_status` (`status`),
    INDEX `idx_content` (`content_type`, `content_id`)
) ENGINE=InnoDB;

-- Table: ban_log
-- Purpose: Track user ban history for audit trail
CREATE TABLE `ban_log` (
    `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT UNSIGNED NOT NULL,
    `banned_by` INT UNSIGNED NOT NULL,
    `reason` TEXT NOT NULL,
    `action_type` ENUM('ban', 'unban') NOT NULL,
    `banned_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `unbanned_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`banned_by`) REFERENCES `users`(`id`) ON DELETE CASCADE,
    INDEX `idx_user_id` (`user_id`),
    INDEX `idx_banned_by` (`banned_by`),
    INDEX `idx_action_type` (`action_type`)
) ENGINE=InnoDB;

-- Seed data for flagged_words
INSERT INTO `flagged_words` (`word`, `category`, `severity`, `auto_action`) VALUES
('fuck', 'profanity', 'medium', 'flag'),
('fucking', 'profanity', 'medium', 'flag'),
('fucked', 'profanity', 'medium', 'flag'),
('shit', 'profanity', 'low', 'flag'),
('damn', 'profanity', 'low', 'flag'),
('bitch', 'profanity', 'medium', 'flag'),
('bastard', 'profanity', 'high', 'flag'),
('asshole', 'profanity', 'high', 'flag'),
('dick', 'profanity', 'high', 'flag'),
('cunt', 'profanity', 'critical', 'reject'),
('nigger', 'hate_speech', 'critical', 'reject'),
('nigga', 'hate_speech', 'critical', 'reject'),
('faggot', 'hate_speech', 'critical', 'reject'),
('slut', 'sexual', 'high', 'flag'),
('whore', 'sexual', 'high', 'flag'),
('porn', 'sexual', 'medium', 'flag'),
('naked', 'sexual', 'low', 'flag'),
('sex', 'sexual', 'low', 'flag'),
('kill', 'violence', 'high', 'flag'),
('murder', 'violence', 'critical', 'flag'),
('rape', 'violence', 'critical', 'flag'),
('terrorist', 'hate_speech', 'high', 'flag'),
('racist', 'hate_speech', 'high', 'flag'),
('hate', 'hate_speech', 'medium', 'flag'),
('spam', 'spam', 'medium', 'flag'),
('click here', 'spam', 'low', 'flag'),
('free money', 'spam', 'high', 'flag'),
('click now', 'spam', 'medium', 'flag'),
('make money', 'spam', 'medium', 'flag'),
('casino', 'spam', 'medium', 'flag'),
('pills', 'spam', 'medium', 'flag'),
('viagra', 'spam', 'medium', 'flag'),
('loan', 'spam', 'low', 'flag'),
('scam', 'spam', 'high', 'flag'),
('fake', 'spam', 'medium', 'flag'),
('urgent', 'spam', 'low', 'flag'),
('act now', 'spam', 'low', 'flag'),
('limited time', 'spam', 'low', 'flag'),
('winner', 'spam', 'high', 'flag'),
('congratulations', 'spam', 'medium', 'flag'),
('click below', 'spam', 'medium', 'flag'),
('get rich', 'spam', 'high', 'flag'),
('no prescription', 'spam', 'medium', 'flag'),
('pump up', 'sexual', 'medium', 'flag'),
('enlarge', 'sexual', 'medium', 'flag'),
('biggest', 'sexual', 'low', 'flag'),
('penis', 'sexual', 'medium', 'flag'),
('vagina', 'sexual', 'medium', 'flag'),
('breast', 'sexual', 'low', 'flag'),
('nude', 'sexual', 'medium', 'flag'),
('boobs', 'sexual', 'medium', 'flag'),
('ass', 'sexual', 'medium', 'flag'),
('butt', 'sexual', 'low', 'flag'),
('horny', 'sexual', 'high', 'flag'),
('nympho', 'sexual', 'high', 'flag'),
('pedo', 'violence', 'critical', 'reject'),
('pedophile', 'violence', 'critical', 'reject'),
('pedo', 'violence', 'critical', 'reject'),
('kill yourself', 'violence', 'critical', 'flag'),
('suicide', 'violence', 'high', 'flag'),
('die', 'violence', 'high', 'flag'),
('blood', 'violence', 'medium', 'flag'),
('gore', 'violence', 'high', 'flag'),
('torture', 'violence', 'high', 'flag'),
('abuse', 'violence', 'high', 'flag'),
('abusive', 'violence', 'high', 'flag'),
('abduct', 'violence', 'high', 'flag'),
('abductor', 'violence', 'high', 'flag'),
('attack', 'violence', 'medium', 'flag'),
('attacker', 'violence', 'medium', 'flag'),
('harm', 'violence', 'medium', 'flag'),
('harmful', 'violence', 'medium', 'flag'),
('hurt', 'violence', 'medium', 'flag'),
('hurting', 'violence', 'medium', 'flag'),
('hit', 'violence', 'low', 'flag'),
('hitting', 'violence', 'low', 'flag'),
('injure', 'violence', 'medium', 'flag'),
('injuring', 'violence', 'medium', 'flag'),
('injury', 'violence', 'medium', 'flag'),
('injured', 'violence', 'medium', 'flag'),
('violence', 'violence', 'high', 'flag'),
('violent', 'violence', 'high', 'flag'),
('aggressive', 'violence', 'medium', 'flag'),
('aggression', 'violence', 'medium', 'flag'),
('aggressor', 'violence', 'medium', 'flag'),
('assault', 'violence', 'high', 'flag'),
('assaulter', 'violence', 'high', 'flag'),
('bully', 'violence', 'medium', 'flag'),
('bullying', 'violence', 'medium', 'flag'),
('bullyer', 'violence', 'medium', 'flag');